### ISSUE TITLE
Identifiers/Insurer's

### ISSUE THREAD

**Issue by Joeyloganpython** [CodeForPhilly/MATchMapper#5]
Identifiers:  Those are insurers? If so can they possibly have more? If so, we may want to create a separate table to relate a provider to many insurers.

**Comment by jkdru** [comment]
That sounds like a great idea. I don't know how consistently NPI entries include comprehensive or current insurance data for each provider (individual providers seem to vary widely in keeping their data updated), but Medicaid data seems to be a major source for public health organizations' data work.
