### ISSUE TITLE
Taxonomy and licenses:  

### ISSUE THREAD

**Issue by Joeyloganpython** [CodeForPhilly/MATchMapper#6]
Taxonomy and licenses:  How is that different than Pals? Should we capture that data in a separate table and relate it to provider? There are 2, but can there be more? If so, it’s worth building that out just like the pals table to have one provider with many licenses.

**Comment by jkdru** [comment]
Great questions. NPI data is maintained by the providers themselves, while PALS is maintained centrally.

Taxonomy listed with NPI is often more specific than in PALS. (For example, both have "Internal Medicine" as an option, but only NPI data sometimes specifies "Internal Medicine Infectious Disease".) We haven't yet compared the two datasets for other possible differences.

The NPI field that has the most multiplicity is practice address. ~10% of providers list 2 or more. (One to two dozen list 3-8 practice sites.) Haven't yet got a good sense of proportions for 1 | 2 | more than 2 licenses.
