### ISSUE TITLE
Provider site reference table: 

### ISSUE THREAD

**Issue by Joeyloganpython** [CodeForPhilly/MATchMapper#7]
There is a table that relates many sites to many providers and vice vera: Is there some sort of data for this?

**Comment by jkdru** [comment]
As with waivers, I think addresses (and sometimes also phone) are the key link between providers and sites. Our sites data is pretty much loadable, though it might work best to talk through those tables when we meet in a few days.

**Comment by jkdru** [comment]
Related to issue #10

By Aug 31 8 PM, will provide separate spreadsheet tabs for each **_listings** ("rec") table:

SITES
-- **samhsa_site_listings** (compare [Aug 24 ("Behavioral_Health...") fresh download](https://drive.google.com/drive/folders/1vJrqc6UXLcJK6_Fzu5jBJ8hjdIAM2peW) with [Apr 29 compilation](https://docs.google.com/spreadsheets/d/1LvJjYj7yTurIkWT0ZCMWnOrRnDoEEwL1VjeM3fY9r0E/edit#gid=848860426))
-- **dbhids_site_listings**
-- **samhsa_site_codes**

PROVIDERS
-- **samhsa_provider_listings**
-- **npi_listings** (just combine [main lode](https://docs.google.com/spreadsheets/d/1Qh9XuD6Rc1LPMC4NibySmh49HJRlmdTV6Ihq98I3TPg/edit#gid=211035413&fvid=1149774637) with 15-25 recent additions)
-- **pals_listings** (change colname to moreinfo_seePALS, retain all recs per accurate person, use 0 for empty top_one rows)
-- **xwaivers** (use provider ID as PK; add col for past_dea_num and missing cert_state, cert_date cols)

**Comment by jkdru** [comment]
@Joeyloganpython, should the new data loads for provider **_listings** incorporate the P-----## IDs already generated in the test loads or let postgreSQL generate them afresh?

-- **sites** table itself is needed to generate site IDs, but has similar chicken/egg issue as **providers** ([rough model, don't use as-is](https://docs.google.com/spreadsheets/d/1LvJjYj7yTurIkWT0ZCMWnOrRnDoEEwL1VjeM3fY9r0E/edit#gid=2696004))
-- **sites** come from multiple rec sources (whereas **providers** currently come only from **samhsa_provider_listings**)

**Comment by jkdru** [comment]
@Joeyloganpython, @atzbencam: Here are the [sheets for nearly load-ready datasets](https://docs.google.com/spreadsheets/d/10Z_WBGPCYwjSNJ9_7ykMdsWafFdJpgknJuhLU0vOub0/edit?usp=sharing) -- one tab per table. Could we look them over tomorrow? Should the new data loads for provider **_listings** incorporate the P-----## IDs already generated in the test loads or let postgreSQL generate them afresh?

**Comment by jkdru** [comment]
Closing this issue to declutter -- will echo keeper points in updated issue for DB 2.0 (Jan/Feb 2021)
