### ISSUE TITLE
Validating Tables and Columns

### ISSUE THREAD

**Issue by Joeyloganpython** [CodeForPhilly/MATchMapper#9]
Two sets of of notes in google doc, will follow up on DB meeting on Wednesday.

**Comment by jkdru** [comment]
Schema notes (key followup in red): [Google Doc for database](https://docs.google.com/document/d/1uPmzQsB5T5pgnrn9ul2AY8ZIQdATZbxm36FdsFy1zsE/edit?usp=sharing).

**Comment by jkdru** [comment]
See [issue #7](https://github.com/CodeForPhilly/MATchMapper/issues/7) for current updates

**Comment by isaacwasserman** [comment]
This issue has gone dormant and will be closed
